- id: changes
        run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          if echo $FILES | grep -q "leonacostaok.json"; then
            echo "json file changed!!"
          else
            echo "no json file changed!!"
          fi
