on: pull_request

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            // Get a list of all issues created by the PR opener
            const creator = context.payload.sender.login
            const pullRequest = github.issues(context.issue.number)
            console.log(pullRequest)
              //issue_number: context.issue.number,
              //owner: context.repo.owner,
