name: deployment

on: pull_request

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
    - name: get list of files in PR
      if: github.event.pull_request.merged == false
      run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          echo $FILES
          if echo $FILES | grep -q "${{ github.actor }}.json"; then
            echo "${{ github.actor }} json file changed!!"
          else
            echo "user has not changed his own file!!"
          fi
